### ISSUE TITLE
How to use OrderedDict()?

### ISSUE THREAD

**Issue by lisah2u** [giodegas/gdg-online-talks#1]
Hi Giovanni, I really appreciated your talk. Well done! We concluded after you introduced OrderedDict and you gave the challenge to sort by frequency. This was not difficult, but I was left with the question of why we might want to use OrderedDict in this particular example. It seems that it is a useful structure to "remember the order entries were added" -- but aren't we sorting after entries have already been added? Is there some other reason why we might prefer OrderedDict over a standard dictionary?

**Comment by giodegas** [comment]
Hi @lisah2u . Thank you for participating to my event.
Yes, orderedDict maybe useful in those applications were you want to remember the given sequence of keywords, or events over time for example, indexed by the timestamp. You can actually build a complete dictionary based application, without using a SQL server, in a key/value store contexts. See for example the NOSQL Redis data structure server http://redis.io which will give you the memory persistence that Python dictionaries cannot supply since they live in memory. Once you developed your algorithm with Python dictionaries you can then easily map to redis keys/hashes/set/ordered sets.

**Comment by lisah2u** [comment]
Great idea. Thanks for making this point!
